## Numpy Practical 1
#### Name : KHWAJA MOHAMMED ABDULLAH
#### Roll no:172     Class : TY-A

In [1]:
import numpy as np

In [2]:
nplist1 = [0,1,2,3,4]

In [3]:
list1 = np.array(nplist1)

In [4]:
nplist2 = [2,3,4,5,5]

In [5]:
list2 = np.array(nplist2)

In [6]:
list1>list2

array([False, False, False, False, False])

In [7]:
list2>list1

array([ True,  True,  True,  True,  True])

In [8]:
list1 != list2

array([ True,  True,  True,  True,  True])

In [9]:
list1>=list2

array([False, False, False, False, False])

In [10]:
list1<=list2

array([ True,  True,  True,  True,  True])

###  Create a numpy array and determine the size occupied by array in memory

In [11]:
from sys import getsizeof

In [12]:
arr1d = np.array(list1)

In [13]:
getsizeof(arr1d) #size in bytes

116

In [14]:
np.sum(arr1d)

10

### Compute sum of all elements across each row and each column of np array

In [15]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]
arr2d = np.array(list2)

In [16]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [17]:
np.sum(arr2d)

18

In [18]:
np.sum(arr2d,axis=0)

array([6, 6, 6])

In [19]:
arr2d.dtype

dtype('int32')

In [20]:
arr2d = np.array(list2,dtype= 'float')

In [21]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [22]:
arr2d = arr2d.astype('int')

In [23]:
arr2d = arr2d.astype('str')

In [24]:
arr2d

array([['1', '1', '1'],
       ['2', '2', '2'],
       ['3', '3', '3']], dtype='<U11')

In [25]:

list1

array([0, 1, 2, 3, 4])

In [26]:
np2list = arr2d.tolist()

In [27]:
np2list

[['1', '1', '1'], ['2', '2', '2'], ['3', '3', '3']]

### Calculate Mean Across Dimension of numpy array 

In [28]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [29]:
arr2d = arr2d.astype('float')

In [30]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [31]:
print('Shape:',arr2d.shape) #this print is used in python3 

Shape: (3, 3)


In [32]:
arr2d.dtype


dtype('float64')

In [33]:
arr2d.size

9

In [34]:
arr2d.ndim

2

In [35]:
arr2d.ndim

2

In [36]:
arr1d.ndim

1

In [37]:
arr1d

array([0, 1, 2, 3, 4])

In [38]:
arr1d[1]

1

In [39]:
arr2d.ndim

2

In [40]:
arr1d.ndim

1

In [41]:
type(arr2d)

numpy.ndarray

In [42]:
arr2d = np.mean(arr2d)

In [43]:
arr2d

2.0

In [44]:
arr2d = np.median(arr2d)

In [45]:
arr2d

2.0

In [46]:
arr2d.min()

2.0

In [47]:
arr1d.min()

0

Statistical Operation 

In [48]:
list3 = [[1,2,3,4],[5,6,7,8],[7,8,4,3]]
arr3d = np.array(list3)

In [49]:
arr3d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 4, 3]])

In [50]:
arr3d.min()

1

In [51]:
arr3d.max()

8

In [52]:
arr3d.squeeze()

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 4, 3]])

In [53]:
arr = arr3d[:2,:2]

In [54]:
arr

array([[1, 2],
       [5, 6]])

In [55]:
arr3d.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 4, 3]])